name: CI
on:
 - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_image:
          - ruby:latest
          - ruby:3.3
        bundle:
          - latest
          - activejob-7.2
        include:
          - ruby_image: ruby:2.6
            bundle: activejob-5.2
          - ruby_image: ruby:2.6
            bundle: activejob-6.1
          - ruby_image: ruby:3.0
            bundle: activejob-5.2
          - ruby_image: ruby:3.0
            bundle: activejob-6.1
    container:
      image: ${{ matrix.ruby_image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and run tests
        run: |
          bundle
          bundle exec appraisal install
          bundle exec appraisal "${{ matrix.bundle }}" rake spec
